# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'analysis_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AnalysisWindow(object):
    def setupUi(self, AnalysisWindow):
        AnalysisWindow.setObjectName("AnalysisWindow")
        AnalysisWindow.resize(989, 533)
        self.centralwidget = QtWidgets.QWidget(AnalysisWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_back = QtWidgets.QPushButton(self.centralwidget)
        self.btn_back.setGeometry(QtCore.QRect(170, 390, 161, 81))
        self.btn_back.setObjectName("btn_back")
        self.btn_exit = QtWidgets.QPushButton(self.centralwidget)
        self.btn_exit.setGeometry(QtCore.QRect(700, 390, 161, 81))
        self.btn_exit.setObjectName("btn_exit")
        self.lbl_segmented_img = QtWidgets.QLabel(self.centralwidget)
        self.lbl_segmented_img.setGeometry(QtCore.QRect(20, 10, 521, 351))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_segmented_img.sizePolicy().hasHeightForWidth())
        self.lbl_segmented_img.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lbl_segmented_img.setFont(font)
        self.lbl_segmented_img.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_segmented_img.setObjectName("lbl_segmented_img")
        self.txt_analysis_result = QtWidgets.QTextBrowser(self.centralwidget)
        self.txt_analysis_result.setGeometry(QtCore.QRect(550, 40, 421, 291))
        self.txt_analysis_result.setObjectName("txt_analysis_result")
        AnalysisWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(AnalysisWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 989, 26))
        self.menubar.setObjectName("menubar")
        AnalysisWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(AnalysisWindow)
        self.statusbar.setObjectName("statusbar")
        AnalysisWindow.setStatusBar(self.statusbar)

        self.retranslateUi(AnalysisWindow)
        QtCore.QMetaObject.connectSlotsByName(AnalysisWindow)

    def retranslateUi(self, AnalysisWindow):
        _translate = QtCore.QCoreApplication.translate
        AnalysisWindow.setWindowTitle(_translate("AnalysisWindow", "MainWindow"))
        self.btn_back.setText(_translate("AnalysisWindow", "BACK"))
        self.btn_exit.setText(_translate("AnalysisWindow", "EXIT"))
        self.lbl_segmented_img.setText(_translate("AnalysisWindow", "No Image"))
